services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  cbenco\PimcorePageBuilderBundle\Document\Areabrick\GrapesEditor:
    tags:
      - {name: pimcore.area.brick, id: grapeseditor}
