
pimcore:
  documents:
    tags:
      map:
        pagebuilder: \cbenco\PimcorePageBuilderBundle\Document\PageBuilderTag
  objects:
    class_definitions:
      data:
        map:
          pagebuilder: \cbenco\PimcorePageBuilderBundle\PageBuilder\ClassDefinition
